services:
  vue:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: articly-client
    ports:
      - "8081:80"
    networks:
      - default

networks:
  default: 
    external: true   
    name: aiko-network